# Generated by Django 3.0 on 2019-12-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=128)),
                ('deadline', models.DateTimeField()),
                ('priority', models.IntegerField()),
                ('do_repeat', models.BooleanField()),
                ('interval', models.DurationField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolistapp.Task')),
            ],
        ),
    ]
